name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        emacs_version:
          - 27.1
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Install emacs-module.h
      run: cp $HOME/.nix-profile/include/emacs-module.h /usr/include/ || ls -l $HOME/.nix-profile/include
    - name: Build jq-impl
      run: mkdir build && cd build && cmake .. && cmake --build .
